export interface IProduct {
    productid: number;
    productcode: string;
    productname: string;
    spec: string;
    materials: string;
    unit: string;
    packunit: string;
    packqty: number;
    m3: number;
    length: number;
    width: number;
    height: number;
    remark1: string;
    remark2: string;
    remark3: string;
    remark4: string;
    remark5: string;
    remark6: string;
    remark7: string;
    remark8: string;
    remark9: string;
    remark10: string;
    useflag: number;
    level1review: number;
    level1name: string;
    level1date: Date | null;
    level2review: number;
    level2name: string;
    level2date: Date | null;
    creater: string;
    createdAt: Date | null;
    updater: string;
    updatedAt: Date | null;
    productareaid: number;
    warehouseid: number;
    del_uuid: number;
    deletedAt: Date | null;
    deleter: string;
}

export class Product implements IProduct {
    productid: number = 0;
    productcode: string = "";
    productname: string = "";
    spec: string = "";
    materials: string = "";
    unit: string = "";
    packunit: string = "";
    packqty: number = 0;
    m3: number = 0;
    length: number = 0;
    width: number = 0;
    height: number = 0;
    remark1: string = "";
    remark2: string = "";
    remark3: string = "";
    remark4: string = "";
    remark5: string = "";
    remark6: string = "";
    remark7: string = "";
    remark8: string = "";
    remark9: string = "";
    remark10: string = "";
    useflag: number = 0;
    level1review: number = 0;
    level1name: string = "";
    level1date: Date | null = new Date();
    level2review: number = 0;
    level2name: string = "";
    level2date: Date | null = new Date();
    creater: string = "";
    createdAt: Date | null = new Date();
    updater: string = "";
    updatedAt: Date | null = new Date();
    productareaid: number = 0;
    warehouseid: number = 0;
    del_uuid: number = 0;
    deletedAt: Date | null = new Date();
    deleter: string = "";
}