import {SaleOrderCreateMxAndProductAndAmt} from "@/module/saleOrder/saleOrderCreateMxAndProductAndAmt";
import {ISaleOrderMxAndProductAndAmt} from "@/module/saleOrder/saleOrderMx";

export class SaleOrderUpdateMxAndProductAndAmt extends SaleOrderCreateMxAndProductAndAmt{

    constructor(saleOrderMxAndProductAndAmt:ISaleOrderMxAndProductAndAmt) {
        super()
        this.agio = saleOrderMxAndProductAndAmt.agio;
        this.agio1 = saleOrderMxAndProductAndAmt.agio1;
        this.agio2 = saleOrderMxAndProductAndAmt.agio2;
        this.amt = saleOrderMxAndProductAndAmt.amt;
        this.batchNo = saleOrderMxAndProductAndAmt.batchNo;
        this.bzprice = saleOrderMxAndProductAndAmt.bzprice;
        this.bzqty = saleOrderMxAndProductAndAmt.bzqty;
        this.createdAt = saleOrderMxAndProductAndAmt.createdAt;
        this.creater = saleOrderMxAndProductAndAmt.creater;
        this.del_uuid = saleOrderMxAndProductAndAmt.del_uuid;
        this.deletedAt = saleOrderMxAndProductAndAmt.deletedAt;
        this.deleter = saleOrderMxAndProductAndAmt.deleter;
        this.exchangeRate = saleOrderMxAndProductAndAmt.exchangeRate;
        this.floatprice1 = saleOrderMxAndProductAndAmt.floatprice1;
        this.floatprice2 = saleOrderMxAndProductAndAmt.floatprice2;
        this.floatprice3 = saleOrderMxAndProductAndAmt.floatprice3;
        this.height = saleOrderMxAndProductAndAmt.height;
        this.kz_materials = saleOrderMxAndProductAndAmt.kz_materials;
        this.kz_materials_d = saleOrderMxAndProductAndAmt.kz_materials_d;
        this.kz_productCode = saleOrderMxAndProductAndAmt.kz_productCode;
        this.kz_productName = saleOrderMxAndProductAndAmt.kz_productName;
        this.kz_remark = saleOrderMxAndProductAndAmt.kz_remark;
        this.kz_spec = saleOrderMxAndProductAndAmt.kz_spec;
        this.kz_spec_d = saleOrderMxAndProductAndAmt.kz_spec_d;
        this.length = saleOrderMxAndProductAndAmt.length;
        this.level1date = saleOrderMxAndProductAndAmt.level1date;
        this.level1name = saleOrderMxAndProductAndAmt.level1name;
        this.level1review = saleOrderMxAndProductAndAmt.level1review;
        this.level2date = saleOrderMxAndProductAndAmt.level2date;
        this.level2name = saleOrderMxAndProductAndAmt.level2name;
        this.level2review = saleOrderMxAndProductAndAmt.level2review;
        this.m3 = saleOrderMxAndProductAndAmt.m3;
        this.materials = saleOrderMxAndProductAndAmt.materials;
        this.materials_d = saleOrderMxAndProductAndAmt.materials_d;
        this.netprice = saleOrderMxAndProductAndAmt.netprice;
        this.openQty = saleOrderMxAndProductAndAmt.openQty;
        this.otherUnit = saleOrderMxAndProductAndAmt.otherUnit;
        this.otherUnitConversionRate = saleOrderMxAndProductAndAmt.otherUnitConversionRate;
        this.outqty = saleOrderMxAndProductAndAmt.outqty;
        this.packqty = saleOrderMxAndProductAndAmt.packqty;
        this.packunit = saleOrderMxAndProductAndAmt.packunit;
        this.price = saleOrderMxAndProductAndAmt.price;
        this.priceqty = saleOrderMxAndProductAndAmt.priceqty;
        this.pricetype = saleOrderMxAndProductAndAmt.pricetype;
        this.printid = saleOrderMxAndProductAndAmt.printid;
        this.productareaid = saleOrderMxAndProductAndAmt.productareaid;
        this.productcode = saleOrderMxAndProductAndAmt.productcode;
        this.productid = saleOrderMxAndProductAndAmt.productid;
        this.productname = saleOrderMxAndProductAndAmt.productname;
        this.rate = saleOrderMxAndProductAndAmt.rate;
        this.rateAmount = saleOrderMxAndProductAndAmt.rateAmount;
        this.ratePrice = saleOrderMxAndProductAndAmt.ratePrice;
        this.remark = saleOrderMxAndProductAndAmt.remark;
        this.remark1 = saleOrderMxAndProductAndAmt.remark1;
        this.remark10 = saleOrderMxAndProductAndAmt.remark10;
        this.remark2 = saleOrderMxAndProductAndAmt.remark2;
        this.remark3 = saleOrderMxAndProductAndAmt.remark3;
        this.remark4 = saleOrderMxAndProductAndAmt.remark4;
        this.remark5 = saleOrderMxAndProductAndAmt.remark5;
        this.remark6 = saleOrderMxAndProductAndAmt.remark6;
        this.remark7 = saleOrderMxAndProductAndAmt.remark7;
        this.remark8 = saleOrderMxAndProductAndAmt.remark8;
        this.remark9 = saleOrderMxAndProductAndAmt.remark9;
        this.remarkmx = saleOrderMxAndProductAndAmt.remarkmx;
        this.saleOrderId = saleOrderMxAndProductAndAmt.saleOrderId;
        this.saleQty = saleOrderMxAndProductAndAmt.saleQty;
        this.spec = saleOrderMxAndProductAndAmt.spec;
        this.spec_d = saleOrderMxAndProductAndAmt.spec_d;
        this.stopQty = saleOrderMxAndProductAndAmt.stopQty;
        this.unit = saleOrderMxAndProductAndAmt.unit;
        this.updatedAt = saleOrderMxAndProductAndAmt.updatedAt;
        this.updater = saleOrderMxAndProductAndAmt.updater;
        this.useflag = saleOrderMxAndProductAndAmt.useflag;
        this.warehouseid = saleOrderMxAndProductAndAmt.warehouseid;
        this.width = saleOrderMxAndProductAndAmt.width;
    }
}