export const LOCALE_CN = {
    // Set Filter
    selectAll: '(选择所有)',
    selectAllSearchResults: '(选择所有搜索结果)',
    searchOoo: '搜索...',
    blanks: '(空白)',
    noMatches: '没有匹配',

    // Number Filter & Text Filter
    filterOoo: '筛选...',
    equals: '等于',
    notEqual: '不等于',
    empty: '选择一个',

    // Number Filter
    lessThan: '小于',
    greaterThan: '大于',
    lessThanOrEqual: '小于或大于',
    greaterThanOrEqual: '大于或等于',
    inRange: '在范围内',
    inRangeStart: '从',
    inRangeEnd: '到',

    // Text Filter
    contains: '包含',
    notContains: '不包含',
    startsWith: '开始于',
    endsWith: '结束于',

    // Date Filter
    dateFormatOoo: 'yyyy-mm-dd',

    // Filter Conditions
    andCondition: '和',
    orCondition: '或',

    // Filter Buttons
    applyFilter: '确定',
    resetFilter: '重置',
    clearFilter: '清空',
    cancelFilter: '取消',

    // Filter Titles
    textFilter: '文本筛选',
    numberFilter: '数字筛选',
    dateFilter: '日期筛选',
    setFilter: '设置筛选',

    // Side Bar
    columns: '列',
    filters: '筛选',

    // columns tool panel
    pivotMode: '主模式',
    groups: '行组',
    rowGroupColumnsEmptyMessage: '拖动到这里可设置行组',
    values: '值',
    valueColumnsEmptyMessage: '拖动到这里进行聚合数据',
    pivots: '列标签',
    pivotColumnsEmptyMessage: '拖动到这里可设置列标签',

    // Header of the Default Group Column
    group: '分组',

    // Other
    loadingOoo: '无数据',
    noRowsToShow: '无数据',
    enabled: '启用',

    // Menu
    pinColumn: '固定列',
    pinLeft: '固定左边',
    pinRight: '固定右边',
    noPin: '取消固定',
    valueAggregation: '值的合并',
    autosizeThiscolumn: '自动设置列大小',
    autosizeAllColumns: '自动设置所有列大小',
    groupBy: '分组依据',
    ungroupBy: '取消分组依据',
    resetColumns: '重置所有列',
    expandAll: '全部展开',
    collapseAll: '全部关闭',
    copy: '复制',
    ctrlC: 'Ctrl+C',
    copyWithHeaders: '复制到头部栏',
    paste: '粘贴',
    ctrlV: 'Ctrl+V',
    export: '导出',
    csvExport: 'CSV导出',
    excelExport: 'Excel导出',

    // Enterprise Menu Aggregation and Status Bar
    sum: '合计',
    min: '最小',
    max: '最大',
    none: '没有',
    count: '数',
    avg: '平均',
    filteredRows: '筛选后的',
    selectedRows: '选中后',
    totalRows: '总行数',
    totalAndFilteredRows: '总筛选行数',
    more: '更多',
    to: '到',
    of: '的',
    page: '页',
    nextPage: '下一页',
    lastPage: '上一页',
    firstPage: '首页',
    previousPage: '前一页',

    // Pivoting
    pivotColumnGroupTotals: '总数',

    // Enterprise Menu (Charts)
    pivotChartAndPivotMode: 'Pivot Chart & Pivot Mode',
    pivotChart: 'Pivot Chart',
    chartRange: 'Chart Range',

    columnChart: 'Column',
    groupedColumn: 'Grouped',
    stackedColumn: 'Stacked',
    normalizedColumn: '100% Stacked',

    barChart: 'Bar',
    groupedBar: 'Grouped',
    stackedBar: 'Stacked',
    normalizedBar: '100% Stacked',

    pieChart: 'Pie',
    pie: 'Pie',
    doughnut: 'Doughnut',

    line: 'Line',

    xyChart: 'X Y (Scatter)',
    scatter: 'Scatter',
    bubble: 'Bubble',

    areaChart: 'Area',
    area: 'Area',
    stackedArea: 'Stacked',
    normalizedArea: '100% Stacked',

    histogramChart: 'Histogram',

    // Charts
    pivotChartTitle: 'Pivot Chart',
    rangeChartTitle: 'Range Chart',
    settings: 'Settings',
    data: 'Data',
    format: 'Format',
    categories: 'Categories',
    defaultCategory: '(None)',
    series: 'Series',
    xyValues: 'X Y Values',
    paired: 'Paired Mode',
    axis: 'Axis',
    navigator: 'Navigator',
    color: 'Color',
    thickness: 'Thickness',
    xType: 'X Type',
    automatic: 'Automatic',
    category: 'Category',
    number: 'Number',
    time: 'Time',
    xRotation: 'X Rotation',
    yRotation: 'Y Rotation',
    ticks: 'Ticks',
    width: 'Width',
    height: 'Height',
    length: 'Length',
    padding: 'Padding',
    spacing: 'Spacing',
    chart: 'Chart',
    title: 'Title',
    titlePlaceholder: 'Chart title - double click to edit',
    background: 'Background',
    font: 'Font',
    top: 'Top',
    right: 'Right',
    bottom: 'Bottom',
    left: 'Left',
    labels: 'Labels',
    size: 'Size',
    minSize: 'Minimum Size',
    maxSize: 'Maximum Size',
    legend: 'Legend',
    position: 'Position',
    markerSize: 'Marker Size',
    markerStroke: 'Marker Stroke',
    markerPadding: 'Marker Padding',
    itemSpacing: 'Item Spacing',
    itemPaddingX: 'Item Padding X',
    itemPaddingY: 'Item Padding Y',
    layoutHorizontalSpacing: 'Horizontal Spacing',
    layoutVerticalSpacing: 'Vertical Spacing',
    strokeWidth: 'Stroke Width',
    offset: 'Offset',
    offsets: 'Offsets',
    tooltips: 'Tooltips',
    callout: 'Callout',
    markers: 'Markers',
    shadow: 'Shadow',
    blur: 'Blur',
    xOffset: 'X Offset',
    yOffset: 'Y Offset',
    lineWidth: 'Line Width',
    normal: 'Normal',
    bold: 'Bold',
    italic: 'Italic',
    boldItalic: 'Bold Italic',
    predefined: 'Predefined',
    fillOpacity: 'Fill Opacity',
    strokeOpacity: 'Line Opacity',
    histogramBinCount: 'Bin count',
    columnGroup: 'Column',
    barGroup: 'Bar',
    pieGroup: 'Pie',
    lineGroup: 'Line',
    scatterGroup: 'X Y (Scatter)',
    areaGroup: 'Area',
    histogramGroup: 'Histogram',
    groupedColumnTooltip: 'Grouped',
    stackedColumnTooltip: 'Stacked',
    normalizedColumnTooltip: '100% Stacked',
    groupedBarTooltip: 'Grouped',
    stackedBarTooltip: 'Stacked',
    normalizedBarTooltip: '100% Stacked',
    pieTooltip: 'Pie',
    doughnutTooltip: 'Doughnut',
    lineTooltip: 'Line',
    groupedAreaTooltip: 'Area',
    stackedAreaTooltip: 'Stacked',
    normalizedAreaTooltip: '100% Stacked',
    scatterTooltip: 'Scatter',
    bubbleTooltip: 'Bubble',
    histogramTooltip: 'Histogram',
    noDataToChart: 'No data available to be charted.',
    pivotChartRequiresPivotMode: 'Pivot Chart requires Pivot Mode enabled.',
    chartSettingsToolbarTooltip: 'Menu',
    chartLinkToolbarTooltip: 'Linked to Grid',
    chartUnlinkToolbarTooltip: 'Unlinked from Grid',
    chartDownloadToolbarTooltip: 'Download Chart',

    // ARIA
    ariaHidden: 'hidden',
    ariaVisible: 'visible',
    ariaChecked: 'checked',
    ariaUnchecked: 'unchecked',
    ariaIndeterminate:'indeterminate',
    ariaColumnSelectAll: 'Toggle Select All Columns',
    ariaInputEditor: 'Input Editor',
    ariaDateFilterInput: 'Date Filter Input',
    ariaFilterInput: 'Filter Input',
    ariaFilterColumnsInput: 'Filter Columns Input',
    ariaFilterValue: 'Filter Value',
    ariaFilterFromValue: 'Filter from value',
    ariaFilterToValue: 'Filter to value',
    ariaFilteringOperator: 'Filtering Operator',
    ariaColumn: 'Column',
    ariaColumnGroup: 'Column Group',
    ariaRowSelect: 'Press SPACE to select this row',
    ariaRowDeselect: 'Press SPACE to deselect this row',
    ariaRowToggleSelection: 'Press Space to toggle row selection',
    ariaRowSelectAll: 'Press Space to toggle all rows selection',
    ariaToggleVisibility: 'Press SPACE to toggle visibility',
    ariaSearch: 'Search',
    ariaSearchFilterValues: 'Search filter values',

    // ARIA LABEL FOR DIALOGS
    ariaLabelColumnMenu: 'Column Menu',
    ariaLabelCellEditor: 'Cell Editor',
    ariaLabelDialog: 'Dialog',
    ariaLabelSelectField: 'Select Field',
    ariaLabelTooltip: 'Tooltip',
    ariaLabelContextMenu: 'Context Menu',
    ariaLabelSubMenu: 'SubMenu',
    ariaLabelAggregationFunction: 'Aggregation Function'

}