export interface IOutbound {
    outboundid: number;
    outboundcode: string;
    outboundtype: number;
    outdate: string;
    deliveryDate: string;
    moneytype: string;
    relatednumber: string;
    remark1: string;
    remark2: string;
    remark3: string;
    remark4: string;
    remark5: string;
    printcount: number;
    level1review: number;
    level1name: string;
    level1date: Date | null;
    level2review: number;
    level2name: string;
    level2date: Date | null;
    creater: string;
    createdAt: Date | null;
    updater: string;
    updatedAt: Date | null;
    operateareaid:number;
    warehouseid: number;
    clientid: number;
    del_uuid: number;
    deletedAt: Date | null;
    deleter: string;
}