export interface IBuy {
    buyid: number;
    buycode: string;
    buyname: string;
    contactperson: string;
    salesman: string;
    ymrep: string;
    phone_no: string;
    tel_no: string;
    email: string;
    address: string;
    moneytype: string;
    useflag: number;
    accountspayabletype: number;
    level1review: number;
    level1name: string;
    level1date: Date;
    level2review: number;
    level2name: string;
    level2date: Date;
    remark1: string;
    remark2: string;
    remark3: string;
    remark4: string;
    remark5: string;
    remark6: string;
    remark7: string;
    remark8: string;
    remark9: string;
    remark10: string;
    creater: string;
    createdAt: Date;
    updater: string;
    updatedAt: Date;
    buyareaid: number;
    operateareaid: number;
    del_uuid: number;
    deleteAt: Date;
    deleter: string;
}

export class Buy implements IBuy {
    buyid: number = 0;
    buycode: string = "";
    buyname: string = "";
    contactperson: string = "";
    salesman: string = "";
    ymrep: string = "";
    phone_no: string = "";
    tel_no: string = "";
    email: string = "";
    address: string = "";
    moneytype: string = "";
    useflag: number = 1;
    accountspayabletype: number = 0;
    level1review: number = 0;
    level1name: string = "";
    level1date: Date = new Date();
    level2review: number = 0;
    level2name: string = "";
    level2date: Date = new Date();
    remark1: string = "";
    remark2: string = "";
    remark3: string = "";
    remark4: string = "";
    remark5: string = "";
    remark6: string = "";
    remark7: string = "";
    remark8: string = "";
    remark9: string = "";
    remark10: string = "";
    creater: string = "";
    createdAt: Date = new Date();
    updater: string = "";
    updatedAt: Date = new Date();
    buyareaid: number = 0;
    operateareaid: number = 0;
    del_uuid: number = 0;
    deleteAt: Date = new Date();
    deleter: string = "";
}